//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaProject.CinemaCervises {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/CinemaServiceDLL")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CinemaProject.CinemaCervises.GenderType GenderType1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CinemaProject.CinemaCervises.Reservation[] ReservationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CinemaProject.CinemaCervises.UserType UserType1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birth {
            get {
                return this.BirthField;
            }
            set {
                if ((this.BirthField.Equals(value) != true)) {
                    this.BirthField = value;
                    this.RaisePropertyChanged("Birth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CinemaProject.CinemaCervises.GenderType GenderType1 {
            get {
                return this.GenderType1Field;
            }
            set {
                if ((this.GenderType1Field.Equals(value) != true)) {
                    this.GenderType1Field = value;
                    this.RaisePropertyChanged("GenderType1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CinemaProject.CinemaCervises.Reservation[] Reservations {
            get {
                return this.ReservationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationsField, value) != true)) {
                    this.ReservationsField = value;
                    this.RaisePropertyChanged("Reservations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CinemaProject.CinemaCervises.UserType UserType1 {
            get {
                return this.UserType1Field;
            }
            set {
                if ((this.UserType1Field.Equals(value) != true)) {
                    this.UserType1Field = value;
                    this.RaisePropertyChanged("UserType1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenderType", Namespace="http://schemas.datacontract.org/2004/07/CinemaServiceDLL")]
    public enum GenderType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://schemas.datacontract.org/2004/07/CinemaServiceDLL")]
    [System.SerializableAttribute()]
    public partial class Reservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CinemaProject.CinemaCervises.RoomNames RoomNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CinemaProject.CinemaCervises.RoomNames RoomName {
            get {
                return this.RoomNameField;
            }
            set {
                if ((this.RoomNameField.Equals(value) != true)) {
                    this.RoomNameField = value;
                    this.RaisePropertyChanged("RoomName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Row {
            get {
                return this.RowField;
            }
            set {
                if ((this.RowField.Equals(value) != true)) {
                    this.RowField = value;
                    this.RaisePropertyChanged("Row");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Seat {
            get {
                return this.SeatField;
            }
            set {
                if ((this.SeatField.Equals(value) != true)) {
                    this.SeatField = value;
                    this.RaisePropertyChanged("Seat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserType", Namespace="http://schemas.datacontract.org/2004/07/CinemaServiceDLL")]
    public enum UserType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Administrator = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Moderator = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AverageUser = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomNames", Namespace="http://schemas.datacontract.org/2004/07/CinemaServiceDLL")]
    public enum RoomNames : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cheddar = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://schemas.datacontract.org/2004/07/CinemaServiceDLL")]
    [System.SerializableAttribute()]
    public partial class Movie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BmpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CinemaProject.CinemaCervises.RatingType RatingType1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RatingValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CinemaProject.CinemaCervises.RoomNames RoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime[] ScreenTimesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bmp {
            get {
                return this.BmpField;
            }
            set {
                if ((object.ReferenceEquals(this.BmpField, value) != true)) {
                    this.BmpField = value;
                    this.RaisePropertyChanged("Bmp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUri {
            get {
                return this.ImageUriField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUriField, value) != true)) {
                    this.ImageUriField = value;
                    this.RaisePropertyChanged("ImageUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CinemaProject.CinemaCervises.RatingType RatingType1 {
            get {
                return this.RatingType1Field;
            }
            set {
                if ((this.RatingType1Field.Equals(value) != true)) {
                    this.RatingType1Field = value;
                    this.RaisePropertyChanged("RatingType1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double RatingValue {
            get {
                return this.RatingValueField;
            }
            set {
                if ((this.RatingValueField.Equals(value) != true)) {
                    this.RatingValueField = value;
                    this.RaisePropertyChanged("RatingValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CinemaProject.CinemaCervises.RoomNames Room {
            get {
                return this.RoomField;
            }
            set {
                if ((this.RoomField.Equals(value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime[] ScreenTimes {
            get {
                return this.ScreenTimesField;
            }
            set {
                if ((object.ReferenceEquals(this.ScreenTimesField, value) != true)) {
                    this.ScreenTimesField = value;
                    this.RaisePropertyChanged("ScreenTimes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RatingType", Namespace="http://schemas.datacontract.org/2004/07/CinemaServiceDLL")]
    public enum RatingType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bad = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Acceptable = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Good = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Excellent = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JustWow = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rating", Namespace="http://schemas.datacontract.org/2004/07/CinemaServiceDLL")]
    [System.SerializableAttribute()]
    public partial class Rating : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CinemaProject.CinemaCervises.RatingType RatetyTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CinemaProject.CinemaCervises.RatingType RatetyType {
            get {
                return this.RatetyTypeField;
            }
            set {
                if ((this.RatetyTypeField.Equals(value) != true)) {
                    this.RatetyTypeField = value;
                    this.RaisePropertyChanged("RatetyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User1 {
            get {
                return this.User1Field;
            }
            set {
                if ((object.ReferenceEquals(this.User1Field, value) != true)) {
                    this.User1Field = value;
                    this.RaisePropertyChanged("User1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comment", Namespace="http://schemas.datacontract.org/2004/07/CinemaServiceDLL")]
    [System.SerializableAttribute()]
    public partial class Comment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNickField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserNick {
            get {
                return this.UserNickField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNickField, value) != true)) {
                    this.UserNickField = value;
                    this.RaisePropertyChanged("UserNick");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CinemaCervises.ICService")]
    public interface ICService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/ValidateUser", ReplyAction="http://tempuri.org/ICService/ValidateUserResponse")]
        CinemaProject.CinemaCervises.User ValidateUser(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/ValidateUser", ReplyAction="http://tempuri.org/ICService/ValidateUserResponse")]
        System.Threading.Tasks.Task<CinemaProject.CinemaCervises.User> ValidateUserAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/CreateUser", ReplyAction="http://tempuri.org/ICService/CreateUserResponse")]
        bool CreateUser(CinemaProject.CinemaCervises.User newUser, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/CreateUser", ReplyAction="http://tempuri.org/ICService/CreateUserResponse")]
        System.Threading.Tasks.Task<bool> CreateUserAsync(CinemaProject.CinemaCervises.User newUser, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/CreatMovie", ReplyAction="http://tempuri.org/ICService/CreatMovieResponse")]
        bool CreatMovie(CinemaProject.CinemaCervises.Movie newMovie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/CreatMovie", ReplyAction="http://tempuri.org/ICService/CreatMovieResponse")]
        System.Threading.Tasks.Task<bool> CreatMovieAsync(CinemaProject.CinemaCervises.Movie newMovie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/GetMovies", ReplyAction="http://tempuri.org/ICService/GetMoviesResponse")]
        CinemaProject.CinemaCervises.Movie[] GetMovies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/GetMovies", ReplyAction="http://tempuri.org/ICService/GetMoviesResponse")]
        System.Threading.Tasks.Task<CinemaProject.CinemaCervises.Movie[]> GetMoviesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/GetImage", ReplyAction="http://tempuri.org/ICService/GetImageResponse")]
        byte[] GetImage(int from, int to, int idx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/GetImage", ReplyAction="http://tempuri.org/ICService/GetImageResponse")]
        System.Threading.Tasks.Task<byte[]> GetImageAsync(int from, int to, int idx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/SetImage", ReplyAction="http://tempuri.org/ICService/SetImageResponse")]
        int SetImage(string imageUri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/SetImage", ReplyAction="http://tempuri.org/ICService/SetImageResponse")]
        System.Threading.Tasks.Task<int> SetImageAsync(string imageUri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/AddRate", ReplyAction="http://tempuri.org/ICService/AddRateResponse")]
        double AddRate(CinemaProject.CinemaCervises.Rating rate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/AddRate", ReplyAction="http://tempuri.org/ICService/AddRateResponse")]
        System.Threading.Tasks.Task<double> AddRateAsync(CinemaProject.CinemaCervises.Rating rate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/Commenting", ReplyAction="http://tempuri.org/ICService/CommentingResponse")]
        CinemaProject.CinemaCervises.Comment[] Commenting(CinemaProject.CinemaCervises.Comment com);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/Commenting", ReplyAction="http://tempuri.org/ICService/CommentingResponse")]
        System.Threading.Tasks.Task<CinemaProject.CinemaCervises.Comment[]> CommentingAsync(CinemaProject.CinemaCervises.Comment com);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICServiceChannel : CinemaProject.CinemaCervises.ICService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CServiceClient : System.ServiceModel.ClientBase<CinemaProject.CinemaCervises.ICService>, CinemaProject.CinemaCervises.ICService {
        
        public CServiceClient() {
        }
        
        public CServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CinemaProject.CinemaCervises.User ValidateUser(string email, string password) {
            return base.Channel.ValidateUser(email, password);
        }
        
        public System.Threading.Tasks.Task<CinemaProject.CinemaCervises.User> ValidateUserAsync(string email, string password) {
            return base.Channel.ValidateUserAsync(email, password);
        }
        
        public bool CreateUser(CinemaProject.CinemaCervises.User newUser, string password) {
            return base.Channel.CreateUser(newUser, password);
        }
        
        public System.Threading.Tasks.Task<bool> CreateUserAsync(CinemaProject.CinemaCervises.User newUser, string password) {
            return base.Channel.CreateUserAsync(newUser, password);
        }
        
        public bool CreatMovie(CinemaProject.CinemaCervises.Movie newMovie) {
            return base.Channel.CreatMovie(newMovie);
        }
        
        public System.Threading.Tasks.Task<bool> CreatMovieAsync(CinemaProject.CinemaCervises.Movie newMovie) {
            return base.Channel.CreatMovieAsync(newMovie);
        }
        
        public CinemaProject.CinemaCervises.Movie[] GetMovies() {
            return base.Channel.GetMovies();
        }
        
        public System.Threading.Tasks.Task<CinemaProject.CinemaCervises.Movie[]> GetMoviesAsync() {
            return base.Channel.GetMoviesAsync();
        }
        
        public byte[] GetImage(int from, int to, int idx) {
            return base.Channel.GetImage(from, to, idx);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetImageAsync(int from, int to, int idx) {
            return base.Channel.GetImageAsync(from, to, idx);
        }
        
        public int SetImage(string imageUri) {
            return base.Channel.SetImage(imageUri);
        }
        
        public System.Threading.Tasks.Task<int> SetImageAsync(string imageUri) {
            return base.Channel.SetImageAsync(imageUri);
        }
        
        public double AddRate(CinemaProject.CinemaCervises.Rating rate) {
            return base.Channel.AddRate(rate);
        }
        
        public System.Threading.Tasks.Task<double> AddRateAsync(CinemaProject.CinemaCervises.Rating rate) {
            return base.Channel.AddRateAsync(rate);
        }
        
        public CinemaProject.CinemaCervises.Comment[] Commenting(CinemaProject.CinemaCervises.Comment com) {
            return base.Channel.Commenting(com);
        }
        
        public System.Threading.Tasks.Task<CinemaProject.CinemaCervises.Comment[]> CommentingAsync(CinemaProject.CinemaCervises.Comment com) {
            return base.Channel.CommentingAsync(com);
        }
    }
}
